version: '3.8'
services:
  backend:
    build:
      context: ./MinVid-API
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./MinVid
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
