version: '3.8'
services:
  backend:
    build:
      context: ./MinVid-API
    ports:
      - "5000:8080"
    networks:
      - app-network
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - C:/DATA:/app/data   # map your host data folder here

  frontend:
    build:
      context: ./MinVid
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network: