FROM node:20 AS builder         
WORKDIR /MinVid	                      
COPY . .                          
RUN npm install                  
RUN npm run build 		          

FROM nginx:alpine  
WORKDIR /MinVid/dist/min-vid/browser	                
COPY --from=builder . /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80                       
CMD ["nginx", "-g", "daemon off;"] 
