FROM node:20 AS builder
WORKDIR /MinVid
COPY . .
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=builder /MinVid/dist/min-vid/browser /usr/share/nginx/html
COPY /MinVid/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
